import uuid
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select

from app.models.order import Order, OrderItem, OrderStatus
from app.models.conversation import Conversation
from app.utils.memo_code import generate_memo_code


class OrderService:
    @staticmethod
    async def create_from_conversation(
        db: AsyncSession, workspace_id: uuid.UUID, conversation: Conversation
    ) -> Order:
        """Create order from collected conversation data. Memo code generated by backend only."""
        context = conversation.context or {}
        order_data = context.get("order_data", {})

        memo_code = generate_memo_code()

        order = Order(
            workspace_id=workspace_id,
            customer_id=conversation.customer_id,
            memo_code=memo_code,
            status=OrderStatus.PENDING,
            total_amount=order_data.get("total_amount", 0),
            customer_phone=order_data.get("phone"),
            customer_address=order_data.get("address"),
            customer_note=order_data.get("note"),
        )
        db.add(order)
        await db.flush()

        for item_data in order_data.get("products", []):
            item = OrderItem(
                order_id=order.id,
                product_id=item_data.get("product_id"),
                product_name=item_data.get("name", ""),
                quantity=item_data.get("quantity", 1),
                unit_price=item_data.get("price", 0),
                subtotal=item_data.get("price", 0) * item_data.get("quantity", 1),
            )
            db.add(item)

        return order

    @staticmethod
    async def get_by_memo_code(db: AsyncSession, memo_code: str) -> Order | None:
        stmt = select(Order).where(Order.memo_code == memo_code)
        result = await db.execute(stmt)
        return result.scalar_one_or_none()

    @staticmethod
    async def get_pending_order_for_customer(
        db: AsyncSession, workspace_id: uuid.UUID, customer_id: uuid.UUID
    ) -> Order | None:
        stmt = select(Order).where(
            Order.workspace_id == workspace_id,
            Order.customer_id == customer_id,
            Order.status.in_([OrderStatus.PENDING, OrderStatus.PAYMENT_SENT]),
        ).order_by(Order.created_at.desc())
        result = await db.execute(stmt)
        return result.scalar_one_or_none()
